#!/usr/bin/env php
<?php

// absolute filesystem path to this web root
define('WWW_DIR', __DIR__ . '/www');

// absolute filesystem path to the application root
define('APP_DIR', __DIR__ . '/app');

// absolute filesystem path to the libraries
define('LIBS_DIR', __DIR__ . '/libs');

// Let bootstrap create Dependency Injection container.
$cofigurator = require APP_DIR . '/bootstrap.php';

$container = $cofigurator->createContainer();

// Run console
if (PHP_SAPI === 'cli') {
	$container->getByType(\Symfony\Component\Console\Application::class)->run();
}